version: '3.9'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    ports:
      - "9091:9091"  # Web UI port
      - "51413:51413" # Torrent port (TCP)
      - "51413:51413/udp" # Torrent port (UDP)
    volumes:
      - ${APPDATA}/transmission/config:/config
      - ${DATADIR}/transmission:/downloads
      - ${DATADIR}/transmission/watch:/watch

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8096:8096" # HTTP Port for Jellyfin
    devices:
      - /dev/dri:/dev/dri  # for hardware transcoding
    volumes:
      - ${APPDATA}/jellyfin/config:/config
      - ${APPDATA}/jellyfin/cache:/cache
      - ${DATADIR}/jellyfin/movies:/media/movies
      - ${DATADIR}/jellyfin/shows:/media/shows