# CLI
brew "mas"        # Mac App Store command-line interface
brew "bash"       # Update Bash to 5.2+ (Apple won't distribute newer versions due to license concerns)
brew "fish"       # User-friendly command-line shell for UNIX-like operating systems
brew "midnight-commander"   # midnight-commander Terminal-based visual file manager
brew "tldr"       # Simplified and community-driven man pages
brew "tree"       # Display directories as trees (with optional color/HTML output)
brew "wget"       # Internet file retriever
brew "imagemagick"# Tools and libraries to manipulate images in many formats
brew "ffmpeg"     # Play, record, convert, and stream audio and video
brew "youtube-dl" # Download YouTube videos from the command-line
brew "speedtest-cli" # Command-line interface for https://speedtest.net bandwidth tests
brew "dockutil"   # Tool for managing dock items
cask "mysides"    # A simple CLI tool for Finder sidebar modification.
brew "pandoc"     # Required by my recipe manager script - Swiss-army knife of markup format conversion.
brew "btop"       # Resource monitor. C++ version and continuation of bashtop and bpytop
brew "gum"        # Tool for glamorous shell scripts
brew "neofetch"   # Fast, highly customisable system info script

# Development tools
brew "git"        # Distributed revision control system
cask "fork"       # GIT client
cask "visual-studio-code"   # Open-source code editor

# Android development
cask "android-studio" # Tools for building Android applications 
cask "temurin"    # Required for ./gradlew projects - JDK from the Eclipse Foundation

# File management
cask "the-unarchiver" # Unpacks archive files
cask "android-file-transfer"  # Transfer files from and to an Android smartphone

# Browser
cask "google-chrome"  # Web browser

# Messaging
#cask "messenger"  # Native desktop app for Messenger (formerly Facebook Messenger)
#cask "whatsapp"   # Native desktop client for WhatsApp
#cask "slack"      # Team communication and collaboration software
#cask "discord"    # Voice and text chat software
#cask "zoom"       # Video communication and virtual meeting platform
#cask "skype"      # Video chat, voice call and instant messaging application

# Media
cask "yt-music"   # YouTube music client
cask "audacity"   # Multi-track audio editor and recorder
mas "iMovie", id: 408981434 # A free video-editing program for Apple users

# Tools
cask "sweet-home3d" # Interior design application
cask "balenaetcher" # Tool to flash OS images to SD cards & USB drives
cask "monitorcontrol" # Tool to control external monitor brightness & volume
cask "philips-hue-sync" # Control your smart light system

# Utilities
cask "chatgpt"    # OpenAI's official ChatGPT desktop app
cask "logi-options+"  # Software for Logitech devices
cask "appcleaner" # Application uninstaller
cask "ukelele"    # Unicode keyboard layout editor
cask "coconutbattery" # Tool to show live information about the batteries in various devices
mas "Magnet", id: 441258766       # Window manager for Mac
mas "Amphetamine", id: 937984704  # Keep-awake utility for macOS

# Gaming
#cask "whisky"     # Wine wrapper built with SwiftUI
#cask "steam"      # Video game digital distribution service
#cask "battle-net" # Blizzard Battle.net online gaming platform
#cask "curseforge" # Download and manage your addons and mods
#cask "epic-games" # Launcher for *Epic Games* games
#cask "origin"     # Play PC games and connect with your friends
#cask "8bitdo-ultimate-software" # Control every piece of your controller
