# CLI
brew "mas"        # Mac App Store command-line interface
cask "kitty"      # GPU-based terminal emulator
brew "bash"       # [Update Bash from version 3.2 to 5.2+ as Apple won’t distribute newer versions due to licences concerns.] - Bourne-Again SHell, a UNIX command interpreter
brew "fish"       # User-friendly command-line shell for UNIX-like operating systems
brew "mc"         # midnight-commander Terminal-based visual file manager
brew "tldr"       # Simplified and community-driven man pages
brew "autojump"   # Shell extension to jump to frequently used directories
brew "thefuck"    # Programmatically correct mistyped console commands
brew "tree"       # Display directories as trees
brew "wget"       # Internet file retriever
cask "gdisk"      # Disk partitioning tool
brew "imagemagick"# Tools and libraries to manipulate images in many formats
brew "ffmpeg"     # Play, record, convert, and stream audio and video
brew "youtube-dl" # Download YouTube videos from the command-line
brew "speedtest-cli" # Command-line interface for https://speedtest.net bandwidth tests
brew "dockutil"   # Tool for managing dock items
cask "mysides"    # A simple CLI tool for Finder sidebar modification.
brew "pandoc"     # [Required by my recipe manager script] - Swiss-army knife of markup format conversion)
brew "btop"       # Resource monitor. C++ version and continuation of bashtop and bpytop

# CLI Rice
brew "gum"        # Tool for glamorous shell scripts
brew "dialog"     # Display user-friendly message boxes from shell scripts
brew "neofetch"   # Fast, highly customisable system info script
brew "tty-clock"  # Digital clock in ncurses
brew "cmatrix"    # Console Matrix
brew "cbonsai"    # Console Bonsai is a bonsai tree generator, written in C using ncurses

# Development tools
brew "git"        # Distributed revision control system
brew "lazygit"    # Simple terminal UI for git commands
cask "fork"       # GIT client
cask "pulsar"     # Text editor
cask "postman"    # Collaboration platform for API development
cask "charles"    # Web debugging Proxy application
#brew "mitmproxy"  # Intercept, modify, replay, save HTTP/S traffic
brew "lorem"      # Lorem ipsum generator for the console

# Android development
cask "android-studio" # Tools for building Android applications
cask "temurin"    # [Required for ./gradlew projects] - JDK from the Eclipse Foundation
brew "scrcpy"     # Display and control your Android device
brew "jadx"       # Dex to Java decompiler

# OTT development
cask "handbrake"  # Open-source video transcoder

# Web development
#cask "hugo"       # Configurable static site generator

# Network
cask "nordlayer"  # Network access security service for business
#cask "nordvpn"    # VPN client for secure internet access and private browsing

# File management
cask "the-unarchiver" # Unpacks archive files
#cask "android-file-transfer"  # Transfer files from and to an Android smartphone
#cask "transmission" # Open-source BitTorrent client

# Browser
cask "google-chrome"  # Web browser

# Security
cask "1Password"  # Password manager that keeps all passwords secure behind one password

# Messaging
cask "messenger"  # Native desktop app for Messenger (formerly Facebook Messenger)
cask "whatsapp"   # Native desktop client for WhatsApp
cask "slack"      # Team communication and collaboration software
cask "discord"    # Voice and text chat software
cask "zoom"       # Video communication and virtual meeting platform
cask "skype"      # Video chat, voice call and instant messaging application

# Media
cask "spotify"    # Music streaming service
cask "spotmenu"   # Spotify and iTunes in the menu bar
cask "vlc"        # Multimedia player
cask "gimp"       # Free and open-source image editor
cask "krita"      # Free and open-source painting and sketching program
cask "inkscape"   # Vector graphics editor
cask "audacity"   # Multi-track audio editor and recorder
mas "iMovie", id: 408981434 # A free video-editing program for Apple users

# Documents
cask "libreoffice"# Free cross-platform office suite, fresh version

# Tools
cask "sweet-home3d" # Interior design application
cask "balenaetcher" # Tool to flash OS images to SD cards & USB drives
cask "reminders-menubar" # Simple menu bar app to view and interact with reminders
brew "monitorcontrol" # Tool to control external monitor brightness & volume

# Utilities
cask "logi-options-plus"  # Software for Logitech devices
cask "appcleaner" # Application uninstaller
cask "ukelele"    # Unicode keyboard layout editor
cask "coconutbattery" # Tool to show live information about the batteries in various devices
cask "clipy"      # Clipboard extension app
mas "Magnet", id: 441258766       # Window manager for Mac
mas "Amphetamine", id: 937984704  # Keep-awake utility for macOS

# Gaming
cask "whisky"     # Wine wrapper built with SwiftUI
cask "steam"      # Video game digital distribution service
cask "battle-net" # Blizzard Battle.net online gaming platform
cask "curseforge" # Download and manage your addons and mods
#cask "epic-games" # Launcher for *Epic Games* games
#cask "origin"     # Play PC games and connect with your friends
#cask "8bitdo-ultimate-software" # Control every piece of your controller
#cask "sixtyforce" # N64 emulator
#cask "mgba"       # Game Boy Advance emulator
